defaults:
  - model_checkpoint
  # - early_stopping
  # - learning_rate_monitor
  - _self_

model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "vae-epoch@{epoch}-step@{step}"
  monitor: "train/loss"
  mode: "min"
  save_last: True
  save_top_k: 0
  every_n_train_steps: 500

# early_stopping:
#   monitor: "val/match_rate"
#   patience: 100
#   mode: "max"
