defaults:
  - ema
  - model_checkpoint
  # - early_stopping
  # - learning_rate_monitor
  - _self_

model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "ldm-epoch@{epoch}-step@{step}"
  monitor: null
  mode: "max"
  save_last: True
  save_top_k: 1
  every_n_epochs: 30
  save_on_train_epoch_end: True

# early_stopping:
#   monitor: "val/valid_rate"
#   patience: 100
#   mode: "max"
